export const LOAD_EVENTS_OF_DAY_REQUEST = 'LOAD_EVENTS_OF_DAY_REQUEST'
export const LOAD_EVENTS_OF_DAY_SUCCESS = 'LOAD_EVENTS_OF_DAY_SUCCESS'
export const LOAD_EVENTS_OF_DAY_FAILURE = 'LOAD_EVENTS_OF_DAY_FAILURE'
